include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    constant_identifier_names: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true
    use_key_in_widget_constructors: false